/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_autumn_myapplication_VadTest */

#ifndef _Included_com_autumn_myapplication_VadTest
#define _Included_com_autumn_myapplication_VadTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniGetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_autumn_myapplication_VadTest_jniGetName
  (JNIEnv *, jobject);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniGetAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniGetAge
  (JNIEnv *, jobject);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniIsMale
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_autumn_myapplication_VadTest_jniIsMale
  (JNIEnv *, jobject);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniGetAdditionResult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniGetAdditionResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniShowSomething
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_autumn_myapplication_VadTest_jniShowSomething
  (JNIEnv *, jobject);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniTestLong
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_autumn_myapplication_VadTest_jniTestLong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniGetVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_autumn_myapplication_VadTest_jniGetVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_autumn_myapplication_VadTest
 * Method:    jniInputVoiceData
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniInputVoiceData
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
