/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stdio.h>

#include <TEmbeddedVad.h>
/* Header for class com_autumn_myapplication_DemoA */

#ifndef _Included_com_autumn_myapplication_DemoA
#define _Included_com_autumn_myapplication_DemoA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_autumn_myapplication_DemoA
 * Method:    jniGetName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_autumn_myapplication_VadTest_jniGetName
        (JNIEnv * env, jobject obj){

    long result = TEmbeddedVad_create("/sdcard");
    //定义一个C语言字符串
    const  char * str = "我来自DemoA.so，我的昵称是CooLoongWu ！" ;
    //转换为Java语言的字符串,c++写法不同
    return env-> NewStringUTF(str);
};

/*
 * Class:     com_autumn_myapplication_DemoA
 * Method:    jniGetAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniGetAge
        (JNIEnv * env, jobject obj){
    return 18;
};

/*
 * Class:     com_autumn_myapplication_DemoA
 * Method:    jniIsMale
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_autumn_myapplication_VadTest_jniIsMale
        (JNIEnv * env , jobject obj){
    return JNI_TRUE;
};

/*
 * Class:     com_autumn_myapplication_DemoA
 * Method:    jniGetAdditionResult
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniGetAdditionResult
        (JNIEnv * env, jobject obj, jint x, jint y){
    return x+y;
};

/*
 * Class:     com_autumn_myapplication_DemoA
 * Method:    jniShowSomething
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_autumn_myapplication_VadTest_jniShowSomething
        (JNIEnv * env, jobject obj){
    __android_log_print(ANDROID_LOG_DEBUG, "VadTest.so wq", "这是来自DemoA.so的jniShowSomething()方法！");
};

JNIEXPORT jlong JNICALL Java_com_autumn_myapplication_VadTest_jniTestLong
        (JNIEnv * env, jobject obj,jstring path){
    const char *str = env->GetStringUTFChars( path, NULL);
    long result = TEmbeddedVad_create(str);
    return result;
};

JNIEXPORT jstring JNICALL Java_com_autumn_myapplication_VadTest_jniGetVersion
        (JNIEnv * env, jobject obj,jlong longAddress){
    const char * resultVersion = TEmbeddedVad_get_version(longAddress);
    return env-> NewStringUTF(resultVersion);
};

JNIEXPORT jint JNICALL Java_com_autumn_myapplication_VadTest_jniInputVoiceData
        (JNIEnv * env, jobject obj, jlong longAddress, jstring voiceData, jint len){
    int result = 0;
    if (longAddress != 0) {
        const char *str = env->GetStringUTFChars( voiceData, NULL);
        result = TEmbeddedVad_charInputVoiceData(longAddress,str,len);
    }
    return result;
};

#ifdef __cplusplus
}
#endif
#endif
